### ISSUE TITLE
Web frontend for configuring builds

### ISSUE THREAD

**Issue by achilleas-k** [G-Node/gin-proc#8]
A web frontend that guides users to set up their builds.  It should give users the ability to configure the most important options (input files, scripts/pipelines to run, output files to be pushed back) and generate a drone.yml (or update an existing one) for the builds.

**Comment by achilleas-k** [comment]
The user should be able to reconfigure the builds by going through the web frontend guide.  Initially, a reconfiguration could start from scratch every time and overwrite any existing drone.yml.  In the future however, it would be nice if the guide could read any existing drone.yml and populate the fields with existing values for the user to edit.

Some up-front **requirements** for the service:
- [ ] When setting up the configuration for the user, the SSH key pair should be generated and set up automatically (see Issue #12).
- [ ] The web service/form should guide the user through specifying at least 3 parts with respect to the processing pipeline:
    - [ ] Input files: This should consist of annexed files to download which our clone plugin container should take care of (see Issue #11).
    - [ ] The processing script or commands (the core processing pipeline).  This can be a snakemake file, for which we can have a special configuration option, or just a shell script.
    - [ ] Output files: List of filenames, directories, or globs/wildcards that will be made available to user for download (either gin-proc branch or special repository, see #6) (see also Issue #7).

**Nice features**
These are extra features that would be nice to have if all else is completed:
- [ ] Notification channel: The user can specify how to be notified of completion (or failure) of the processing pipeline.
- [ ] Editing for existing drone.yml: It should be possible for

**Comment by mrinalwahal** [comment]
We are already taking input files for Snakemake workflows. As well as output files to be pushed back to `gin-proc`  branch. Let's discuss the second option of taking inputs for processing commands/scripts for Snakemake workflows in the next discussion.

In nice/extra features:

1.  Notification Channels are already encoded. We can give the user's the option of getting notified on their preferred handles.
2.  Let's discuss the drone pipeline GUI in the next discussion.
